name: build
on:
    push:
        branches: [ '*' ]
        tags: [ '*' ]
    pull_request:
        branches: [ '*' ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v3
                with:
                    java-version: 1.8
            -   name: get tag
                id: get_tag
                run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            -   name: maven build
                env:
                    TAG: ${{ steps.get_tag.outputs.tag }}
                    GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
                    GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
                    GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                    SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                    SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                    COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
                run: |
                    if echo "${TAG}" | egrep '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$'
                    then
                        # the tag looks like a version number: proceed with release
                        echo ${GPG_SECRET_KEY} | base64 --decode | gpg --import --no-tty --batch --yes
                        echo ${GPG_OWNERTRUST} | base64 --decode | gpg --import-ownertrust --no-tty --batch --yes
                        mvn -ntp versions:set -DnewVersion=${TAG}
                        mvn -ntp -s .github/settings.xml -Prelease deploy jacoco:report coveralls:report -DrepoToken=${COVERALLS_TOKEN}
                    else
                        # this is a regular build
                        mvn -ntp install
                    fi
